### ISSUE TITLE
App documents crashes my file manager 

### ISSUE THREAD

**Issue by onos1** [billthefarmer/diary#51]
#### Expected behavior
After saving file from diary app, expected whenever am to open them from my file manager they should open in diary app.

#### Actual behavior
After clicking on the saved files, a crash pop up displays

#### How to reproduce
- download diary app latest version [here](https://f-droid.org/repository/browse/?fdid=org.billthefarmer.diary)
- create an event by using go-to to date after tapping the three dots at the top right corner 
- after writing your desired text or file, save it by clicking the tick button below 
- go-to your file manager 
- locate the diary app folder, saved as diary by default 
- open it and locate the date number of your saved file in `.txt` format 
Crash pop up 

* mobile : Infinix note 4
* Operating system: android 7.0
* version: 1.27
* file manager: Infinix note 4 mobile file manager (v1.0)

#### Recording Of The Bug
https://youtu.be/c1REek15-lc

# Log cat to reproduce the bug 
![diarycrash.txt](undefined)

# some copied and pasted part of the logcat referring to the diary app alone 
`04-20 10:39:23.502 14520 14520 E AndroidRuntime: FATAL EXCEPTION: main
04-20 10:39:23.502 14520 14520 E AndroidRuntime: Process: org.billthefarmer.diary, PID: 14520
04-20 10:39:23.502 14520 14520 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.billthefarmer.diary/org.billthefarmer.diary.Editor}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
04-20 10:39:23.502 14520 14520 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
04-20 10:39:23.502 14520 14520 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
04-20 10:39:23.502 14520 14520 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-20 10:39:23.502 14520 14520 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
04-20 10:39:23.502 14520 14520 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
04-20 10:39:23.502 14520 14520 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
04-20 10:39:23.502 14520 14520 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6251)
04-20 10:39:23.502 14520 14520 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 10:39:23.502 14520 14520 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1073)
04-20 10:39:23.502 14520 14520 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
04-20 10:39:23.502 14520 14520 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
04-20 10:39:23.502 14520 14520 E AndroidRuntime: 	at org.billthefarmer.diary.Editor.onCreate(Editor.java:81)
04-20 10:39:23.502 14520 14520 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6687)
04-20 10:39:23.502 14520 14520 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
04-20 10:39:23.502 14520 14520 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
04-20 10:39:23.502 14520 14520 E AndroidRuntime: 	... 9 more
04-20 10:57:50.770 20312 20312 E AndroidRuntime: FATAL EXCEPTION: main
04-20 10:57:50.770 20312 20312 E AndroidRuntime: Process: org.billthefarmer.diary, PID: 20312
04-20 10:57:50.770 20312 20312 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.billthefarmer.diary/org.billthefarmer.diary.Editor}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
04-20 10:57:50.770 20312 20312 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
04-20 10:57:50.770 20312 20312 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
04-20 10:57:50.770 20312 20312 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-20 10:57:50.770 20312 20312 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
04-20 10:57:50.770 20312 20312 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
04-20 10:57:50.770 20312 20312 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
04-20 10:57:50.770 20312 20312 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6251)
04-20 10:57:50.770 20312 20312 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 10:57:50.770 20312 20312 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1073)
04-20 10:57:50.770 20312 20312 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
04-20 10:57:50.770 20312 20312 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
04-20 10:57:50.770 20312 20312 E AndroidRuntime: 	at org.billthefarmer.diary.Editor.onCreate(Editor.java:81)
04-20 10:57:50.770 20312 20312 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6687)
04-20 10:57:50.770 20312 20312 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
04-20 10:57:50.770 20312 20312 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
04-20 10:57:50.770 20312 20312 E AndroidRuntime: 	... 9 more
04-20 11:11:38.261 23197 23197 E AndroidRuntime: FATAL EXCEPTION: main
04-20 11:11:38.261 23197 23197 E AndroidRuntime: Process: org.billthefarmer.diary, PID: 23197
04-20 11:11:38.261 23197 23197 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.billthefarmer.diary/org.billthefarmer.diary.Editor}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
04-20 11:11:38.261 23197 23197 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
04-20 11:11:38.261 23197 23197 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
04-20 11:11:38.261 23197 23197 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-20 11:11:38.261 23197 23197 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
04-20 11:11:38.261 23197 23197 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
04-20 11:11:38.261 23197 23197 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
04-20 11:11:38.261 23197 23197 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6251)
04-20 11:11:38.261 23197 23197 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 11:11:38.261 23197 23197 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1073)
04-20 11:11:38.261 23197 23197 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
04-20 11:11:38.261 23197 23197 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
04-20 11:11:38.261 23197 23197 E AndroidRuntime: 	at org.billthefarmer.diary.Editor.onCreate(Editor.java:81)
04-20 11:11:38.261 23197 23197 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6687)
04-20 11:11:38.261 23197 23197 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
04-20 11:11:38.261 23197 23197 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
04-20 11:11:38.261 23197 23197 E AndroidRuntime: 	... 9 more
04-20 11:25:06.115 25589 25589 E AndroidRuntime: FATAL EXCEPTION: main
04-20 11:25:06.115 25589 25589 E AndroidRuntime: Process: org.billthefarmer.diary, PID: 25589
04-20 11:25:06.115 25589 25589 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.billthefarmer.diary/org.billthefarmer.diary.Editor}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
04-20 11:25:06.115 25589 25589 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
04-20 11:25:06.115 25589 25589 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
04-20 11:25:06.115 25589 25589 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-20 11:25:06.115 25589 25589 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
04-20 11:25:06.115 25589 25589 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
04-20 11:25:06.115 25589 25589 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
04-20 11:25:06.115 25589 25589 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6251)
04-20 11:25:06.115 25589 25589 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 11:25:06.115 25589 25589 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1073)
04-20 11:25:06.115 25589 25589 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
04-20 11:25:06.115 25589 25589 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
04-20 11:25:06.115 25589 25589 E AndroidRuntime: 	at org.billthefarmer.diary.Editor.onCreate(Editor.java:81)
04-20 11:25:06.115 25589 25589 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6687)
04-20 11:25:06.115 25589 25589 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
04-20 11:25:06.115 25589 25589 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
04-20 11:25:06.115 25589 25589 E AndroidRuntime: 	... 9 more
04-21 00:32:04.280 30270 30270 E AndroidRuntime: FATAL EXCEPTION: main`

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@onos/crash-occurred-when-saved-files-are-opened">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by billthefarmer** [comment]
According to your crash dump the file manager appears to be sending a null Uri to the Diary app. There are several points:
* As the diary entry is a text file the file manager should offer the user the opportunity to open the file with any app than can view or edit a text file. I didn't see that happen.
* The file was sent to the text editor included in the Diary app for editing CSS style files as a convenience for users.
* The Diary app won't open text files sent to it as diary entries. It wasn't designed that way. It will open them as test files in the editor if the file manager plays by the rules and actually sends a valid Uri.
* I found a download for the Infinix file manager and installed it on my test device with a view to test it and find out exactly what it does send, if anything. However it crashes immediately on startup attempting to access a non-existent API which I assume exists in Infinix phones.
* That again is poor design, it should either refuse to install or pop up a message telling the user why it won't work.
* If you want me to pursue this you will need to install [Intent Intercept](https://f-droid.org/packages/de.k3b.android.intentintercept) and turn on `Enable interception` to capture the intent from the file manager. You should get something like this, which is a diary entry sent from the built in file manager. You can see the intent contains an Uri as expected:

![screenshot_20180421-182357](https://user-images.githubusercontent.com/3448386/39087001-ad86eea8-4591-11e8-8e9f-c109541a8dc2.png)
