### ISSUE TITLE
Bug: App crashed when I deny access and I tried to add a media.

### ISSUE THREAD

**Issue by darewealth** [billthefarmer/diary#96]
### Describe the bug.
When I deny access and tried to add media to the app, I clicked the add media button and I selected a media file, and the app crashed. 

### Steps to reproduce.
* Launch the app

* Deny all access

* Click on 3 dots at the top by the right

* Then click on  add media and choose any media

* See the error

### Expected Behaviour
I expect to see information that I need to grant access to use this feature and not a  crash.

### Screen recording.
https://youtu.be/e9_WsOsJGvE

### Devices and Versions

Device: [Gionee X1]

Version [7.0]

App version [1.49]

### Log
```06-24 18:12:21.993 26404 26404 E AndroidRuntime: FATAL EXCEPTION: main
06-24 18:12:21.993 26404 26404 E AndroidRuntime: Process: org.billthefarmer.diary, PID: 26404
06-24 18:12:21.993 26404 26404 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:4847 flg=0x1 }} to activity {org.billthefarmer.diary/org.billthefarmer.diary.Diary}: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
06-24 18:12:21.993 26404 26404 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3714)
06-24 18:12:21.993 26404 26404 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3757)
06-24 18:12:21.993 26404 26404 E AndroidRuntime: 	at android.app.ActivityThread.-wrap16(ActivityThread.java)
06-24 18:12:21.993 26404 26404 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
06-24 18:12:21.993 26404 26404 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-24 18:12:21.993 26404 26404 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-24 18:12:21.993 26404 26404 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
06-24 18:12:21.993 26404 26404 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-24 18:12:21.993 26404 26404 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
06-24 18:12:21.993 26404 26404 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)
06-24 18:12:21.993 26404 26404 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
06-24 18:12:21.993 26404 26404 E AndroidRuntime: 	at java.io.File.fixSlashes(File.java:183)
06-24 18:12:21.993 26404 26404 E AndroidRuntime: 	at java.io.File.<init>(File.java:130)
06-24 18:12:21.993 26404 26404 E AndroidRuntime: 	at org.billthefarmer.diary.FileUtils.getMimeType(FileUtils.java:218)
06-24 18:12:21.993 26404 26404 E AndroidRuntime: 	at org.billthefarmer.diary.Diary.onActivityResult(Diary.java:667)
06-24 18:12:21.993 26404 26404 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6510)
06-24 18:12:21.993 26404 26404 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3710)```

**Comment by billthefarmer** [comment]
Because the app needs access to storage to read and write diary pages I made the decision that the app just wouldn't work if the user persistently denies access, rather than get stuck in a loop continually asking permission. I assume users who sideload this app or get it from F-Droid must have some tech ability. But I missed this one, it will be fixed in the next version.
